Repository Miso-Code/sportapp-back, pull requests merged in 2024-05, with the labels that each got.

#66 Fix: Fix error with ping and service env variable
  infra/terraform/aws/dev/services/sport-events/main.tf
  infra/terraform/aws/prod/services/sport-events/main.tf
  infra/terraform/aws/qa/services/sport-events/main.tf
  projects/sport-events/main.py
Labels: bugfix

#69 Refactor: PSA-212 refactor services to support nutritional plan generation
  projects/nutritional-plans/app/services/external.py
  projects/sport-sessions/app/routes/__init__.py
  projects/training-plans/main.py
  projects/users/app/config/settings.py
  projects/users/app/models/schemas/profiles_schema.py
  projects/users/app/models/schemas/schema.py
  projects/users/app/models/users.py
  projects/users/app/services/external.py
  projects/users/app/services/users.py
  projects/users/app/utils/utils.py
  projects/users/tests/integration/users_test.py
  projects/users/tests/unit/models/mappers/mapper_test.py
  projects/users/tests/unit/models/schemas/profiles_schema_test.py
  projects/users/tests/unit/models/schemas/schema_test.py
  projects/users/tests/unit/services/external_test.py
  projects/users/tests/unit/services/users_test.py
  projects/users/tests/utils/users_util.py
Labels: refactor

#70 Refactor: Add test notification for alerts service
  infra/terraform/aws/dev/services/alerts/main.tf
  infra/terraform/aws/prod/services/alerts/main.tf
  infra/terraform/aws/qa/services/alerts/main.tf
  projects/alerts/app/firebase/firebase.py
  projects/alerts/app/models/schemas/schema.py
  projects/alerts/app/routes/alerts_routes.py
  projects/alerts/app/services/alerts.py
  projects/alerts/app/tasks/prioritizer.py
  projects/alerts/tests/unit/routes/alerts_routes_test.py
  projects/alerts/tests/unit/services/alerts_test.py
Labels: refactor

#71 feat: PSA-204 added location base filtering on sport get all events
  projects/sport-events/app/config/settings.py
  projects/sport-events/app/routes/sport_events_routes.py
  projects/sport-events/app/services/sport_events.py
  projects/sport-events/main.py
  projects/sport-events/tests/integration/sport_events_test.py
  projects/sport-events/tests/unit/routes/sport_events_test.py
  projects/sport-events/tests/unit/services/sport_events_test.py
Labels: feature

#72 Feature: PSA-123 added suggested product endpoint with filters
  projects/business-partners/app/models/business_partners.py
  projects/business-partners/app/models/schemas/schema.py
  projects/business-partners/app/routes/business_partners_routes.py
  projects/business-partners/app/services/business_partners.py
  projects/business-partners/poetry.lock
  projects/business-partners/pyproject.toml
  projects/business-partners/tests/integration/business_partners_test.py
  projects/business-partners/tests/unit/models/business_partners_test.py
  projects/business-partners/tests/unit/routes/business_partners_routes_test.py
  projects/business-partners/tests/unit/services/business_partners_test.py
  projects/business-partners/tests/utils/business_partners_util.py
Labels: feature

#74 Fix: Fix error with name too long for target group
  infra/terraform/aws/dev/services/adverse-incidents-provider/main.tf
  infra/terraform/aws/prod/services/adverse-incidents-provider/main.tf
  infra/terraform/aws/qa/services/adverse-incidents-provider/main.tf
Labels: bugfix

#75 Fix: Fix error with env in adverse-incidents-provider
  projects/adverse-incidents-provider/app/config/settings.py
Labels: bugfix

#76 Fix: Fix error with wrong environment variables in adverse-incidents and sport-sessions
  infra/terraform/aws/dev/services/adverse-incidents/main.tf
  infra/terraform/aws/dev/services/sport-sessions/main.tf
  infra/terraform/aws/prod/services/adverse-incidents/main.tf
  infra/terraform/aws/prod/services/sport-sessions/main.tf
  infra/terraform/aws/qa/services/adverse-incidents/main.tf
  infra/terraform/aws/qa/services/sport-sessions/main.tf
Labels: bugfix

#77 Fix: Add missing env vars for nutritional plans
  infra/terraform/aws/dev/services/nutritional-plans/main.tf
  infra/terraform/aws/prod/services/nutritional-plans/main.tf
  infra/terraform/aws/qa/services/nutritional-plans/main.tf
Labels: bugfix

#78 Fix: Fix overall bugs in alerts and nutritional-plans
  infra/terraform/aws/dev/services/alerts/main.tf
  projects/nutritional-plans/Dockerfile
  projects/nutritional-plans/app/exceptions/exceptions.py
  projects/nutritional-plans/app/services/external.py
  projects/nutritional-plans/main.py
  projects/nutritional-plans/tests/unit/services/external_test.py
Labels: bugfix

#79 Fix: Fix overall errors in nutritional-plan creation
  infra/terraform/aws/dev/services/business-partners/main.tf
  infra/terraform/aws/prod/services/business-partners/main.tf
  infra/terraform/aws/qa/services/business-partners/main.tf
  projects/nutritional-plans/app/services/external.py
  projects/nutritional-plans/app/services/nutritional_plans.py
  projects/nutritional-plans/tests/unit/services/external_test.py
  projects/users/app/routes/users_routes.py
  projects/users/app/services/external.py
  projects/users/app/services/users.py
  projects/users/tests/integration/users_test.py
  projects/users/tests/unit/services/external_test.py
Labels: bugfix

#81 feat: Add security tests document (README) with images of execution
  .github/dependabot.yml
  .github/workflows/create-release.yml
  tests/load/.gitkeep
  tests/security/README.md
  tests/security/resources/api_gateway_authorizer.png
  tests/security/resources/aws_ecr.png
  tests/security/resources/dependabot_report.png
  tests/security/resources/git_guardian.png
  tests/security/resources/secrets_manager.png
  tests/security/resources/snyk.png
  tests/security/resources/zap.png
  tests/stress/.gitkeep
Labels: security

#82 Fix: Fix error with dependabot.yml file
  .github/dependabot.yml
Labels: bugfix

#84 Fix: Update services using alerts to fix issues
  projects/adverse-incidents/app/models/schemas/schema.py
  projects/adverse-incidents/app/services/adverse_incidents.py
  projects/adverse-incidents/app/services/external.py
  projects/adverse-incidents/tests/unit/__init__.py
  projects/adverse-incidents/tests/unit/services/external_test.py
  projects/alerts/app/tasks/prioritizer.py
  projects/alerts/app/tasks/publisher.py
  projects/alerts/tests/unit/tasks/prioritizer_test.py
  projects/alerts/tests/unit/tasks/publisher_test.py
  projects/nutritional-plans/app/models/schemas/schema.py
  projects/nutritional-plans/app/services/nutritional_plans.py
  projects/nutritional-plans/tests/unit/utils/utils_test.py
Labels: bugfix

#86 Feature: Add load testing tests with new service
  .github/workflows/build-and-push-images.yml
  .github/workflows/check-pr-users-auth.yml
  .github/workflows/sync-sonar-coverage.yml
  .pre-commit-config.yaml
  infra/scripts/sync_container_repositories.sh
  projects/users-auth/.gitignore
  projects/users-auth/.nvmrc
  projects/users-auth/Dockerfile
  projects/users-auth/jest.config.js
  projects/users-auth/package.json
  projects/users-auth/sonar-project.properties
  projects/users-auth/src/__tests__/server.test.js
  projects/users-auth/src/app.js
  projects/users-auth/src/config/index.js
  projects/users-auth/src/controllers/__tests__/users.controller.test.js
  projects/users-auth/src/controllers/users.controller.js
  projects/users-auth/src/db/__tests__/db.test.js
  projects/users-auth/src/db/db.js
  projects/users-auth/src/db/index.js
  projects/users-auth/src/index.js
  projects/users-auth/src/models/__tests__/card.model.test.js
  projects/users-auth/src/models/enums/index.js
  projects/users-auth/src/models/index.js
  projects/users-auth/src/models/schemas/__tests__/login.schema.test.js
  projects/users-auth/src/models/schemas/__tests__/user.schema.test.js
  projects/users-auth/src/models/schemas/index.js
  projects/users-auth/src/models/schemas/login.schema.js
  projects/users-auth/src/models/schemas/user.schema.js
  projects/users-auth/src/models/user.model.js
  projects/users-auth/src/routes/__tests__/users.routes.test.js
  projects/users-auth/src/routes/users.routes.js
  projects/users-auth/src/security/__tests__/jwt.test.js
  projects/users-auth/src/security/jwt.js
  projects/users-auth/src/server.js
  projects/users-auth/src/services/__tests__/user.service.test.js
  projects/users-auth/src/services/user.service.js
  projects/users-auth/src/utils/index.js
  projects/users-auth/test/integration.test.js
  projects/users-auth/yarn.lock
  projects/users/app/security/passwords.py
  projects/users/app/utils/utils.py
  projects/users/tests/unit/security/passwords_test.py
  projects/users/tests/unit/services/users_test.py
  shared/.gitkeep
  tests/load/.gitkeep
  tests/load/README.md
  tests/load/load_test.jmx
  tests/load/resources/node.png
  tests/load/resources/python.png
Labels: feature

#87 Feat: Add stress tests
  projects/users-auth/package.json
  tests/load/README.md
  tests/security/README.md
  tests/stress/.gitkeep
  tests/stress/README.md
  tests/stress/resources/node.png
  tests/stress/resources/python.png
  tests/stress/stress_test.jmx
Labels: feature

#129 Refactor: Apply dependabot security updates
  poetry.lock
  projects/adverse-incidents-provider/poetry.lock
  projects/adverse-incidents-provider/pyproject.toml
  projects/adverse-incidents/poetry.lock
  projects/adverse-incidents/pyproject.toml
  projects/alerts/poetry.lock
  projects/alerts/pyproject.toml
  projects/authorizer/poetry.lock
  projects/authorizer/pyproject.toml
  projects/business-partners/poetry.lock
  projects/business-partners/pyproject.toml
  projects/nutritional-plans/poetry.lock
  projects/nutritional-plans/pyproject.toml
  projects/sport-events/poetry.lock
  projects/sport-events/pyproject.toml
  projects/sport-sessions/poetry.lock
  projects/sport-sessions/pyproject.toml
  projects/sports/poetry.lock
  projects/sports/pyproject.toml
  projects/training-plans/poetry.lock
  projects/training-plans/pyproject.toml
  projects/users/poetry.lock
  projects/users/pyproject.toml
  pyproject.toml
Labels: refactor
